### ISSUE TITLE
How to make CSS auto prefixer work?

### ISSUE THREAD

**Issue by nulldev07** [alan-agius4/ng-mono-repo-starter#68]
Hey! Thanks a lot for this work. I am trying to make CSS auto prefixer work in this repo, but am unable to do it. 

Here is what I did:

1. Cloned your repo
2. Added `.browserslistrc` to the root folder with the following contents:
```
> 0.5%
last 2 versions
Firefox ESR
not dead
IE 11
```
3.  In `package-1/.../skeleton.component.scss`:
```css
:host {
	display: block;
	background: linear-gradient(red, yellow);
}
```
4. `npm run build`

I am expecting the `linear-gradient` to be auto-prefixed in `dist/fesm5/speedy-package-1.js`. But here is what I get:
```js
    SkeletonComponent.decorators = [
        { type: Component, args: [{
                    selector: "obg-skeleton",
                    template: "<h1>Sample</h1>",
                    preserveWhitespaces: false,
                    styles: [":host{display:block;background:linear-gradient(red,#ff0)}"]
                }] }
    ];
```

Am I missing something?

**Comment by alan-agius4** [comment]
Afaik, you need to place the config parallel to the library package.json.

Can you give it a try? If it doesn’t work I will try to look into this
later today.

**Comment by nulldev07** [comment]
Moving `.browserslistrc` into `package-1` is producing the same results - no prefixes.

Even if that worked, would'nt it would be ideal to place `.browserslistrc` at the monorepo root level? [https://github.com/browserslist/browserslist#queries](https://github.com/browserslist/browserslist#queries)

**Comment by alan-agius4** [comment]
I looked into this further, and it looks like it's working correct. For the browsers you specified there shouldn't be a prefixed.

If I change `last 2 versions` to last 4 versions` they get prefixed as expected.

**Comment by nulldev07** [comment]
You are right. I did not verify this this from caniuse.com. Thanks a lot for quick help!
