### ISSUE TITLE
Does this project support AOT out of the box

### ISSUE THREAD

**Issue by no-more** [alan-agius4/ng-mono-repo-starter#73]
Hello,

First of all this looks like a very interesting project, and exactly what I need to start refactoring my project. Thanks for that.

I didn't find any indication about AOT support, does the project allow it? Is there any build tasks for AOT ?

Thanks a lot.

Best regards.

**Comment by alan-agius4** [comment]
Hi, `ng-packagr` only builds packages in AOT mode

**Comment by no-more** [comment]
Wow, fast response.

Thanks a lot.
