### ISSUE TITLE
Newbie questions

### ISSUE THREAD

**Issue by no-more** [alan-agius4/ng-mono-repo-starter#74]
Sorry for my questions,
I'm new to angular cli and mono repository concept. I've been working on a angular project since angular 2 beta (or maybe even alpha) and at this time cli was not available. I've build up several tools in order to automate most of the tasks. But now I'd like to refactor everything in a more standard way in order to be able to benefit of AOT and monorepository which seems to better suit my project.

I hope I won't bother you with my questions:

1. Is it possible to develop application with this template ? It looks great for lib component and already provide examples. But would it be possible to include along side several applications which use those components ?
2. If yes would it be possible to implement an app skeleton with all the build and serve process ?
3. It would be great to implement `schematics` in order to be able to use `ng` cli to bootstrap new lib/component/apps. Maybe it's not possible, I don't know much about it.
4. It seems you started this project with `angular 5`, I've read around that angular 6 had a major improvement on the `cli`, including `workspace` with a main `angular.json` config file at the root. Is this project already taking benefit of those improvements ? If not do you plan it ?

Thanks a lot.

**Comment by alan-agius4** [comment]
1) This is mainly for libraries. However, I do suggest that you look into Angular-CLI for an application + library mono repo.

2) This project already uses Angular 6.
